services:
  - type: web
    name: kibris-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: THE_ODDS_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: kibris_db




